package com.richards.accountnumbergeneration.service.impl;

import com.richards.accountnumbergeneration.service.AccountNumberService;
import org.springframework.stereotype.Service;

import static com.richards.accountnumbergeneration.util.Utils.*;

@Service
public class AccountNumberServiceImpl implements AccountNumberService {
    public String generateAccount() {
        int[] products = new int[]{3, 7, 3, 3, 7, 3, 3, 7, 3, 3, 7, 3};
        int sumOfProducts = 0;
        String autoGeneratedCode = autogenerateDigit();
        String allCodes = CBN_CODE + autoGeneratedCode;

        for(int i = 0 ; i < allCodes.length() ; i++) {
            int codeDigit = Integer.parseInt(""+allCodes.charAt(i));
            sumOfProducts += codeDigit * products[i];
        }

        int modulusOfSum = sumOfProducts % 10;
        String checkDigit;
        if(modulusOfSum != 0) checkDigit = ""+(10 - modulusOfSum);
        else checkDigit ="0";

        return autoGeneratedCode+checkDigit;
    }
}
