package com.richards.accountnumbergeneration.util;

public class Utils {
    public static final String CBN_CODE = "011";

    public static String autogenerateDigit() {
        String code = "";
        int range = 9;
        for(int i = 0 ; i < range ; i++) {
            int rand = (int) (Math.random() * range);
            code += ""+ rand;
        }
        return code;
    }
}
